import {
  CoverPage,
  ChapterBanner,
  AnswerKeyBlock,
  SectionRule,
} from "@/components/workbook";

export default function AvionicsAnswersPage() {
  return (
    <div className="page-root">
      <CoverPage
        title="Introduction to Avionics"
        subtitle="Answer Key — Teacher Edition"
        author="Based on Arms of Deliverance by Tricia Goyer"
        series="WWII Curriculum Series"
        description="Model answers and grading guidance for all six weeks. Math answers show full work. Open-ended questions include rubric notes."
      />

      <SectionRule />

      {/* ===== WEEK 1 ===== */}
      <ChapterBanner chapter="Week 1" title="Four Forces and the B-17 — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Four Forces of Flight:</strong></p>
        <ul className="answer-list">
          <li><em>Lift</em> — upward aerodynamic force generated by the wings acting on air</li>
          <li><em>Weight (Gravity)</em> — downward force equal to mass × g</li>
          <li><em>Thrust</em> — forward force produced by engines and propellers</li>
          <li><em>Drag</em> — rearward aerodynamic resistance opposing forward motion</li>
        </ul>
        <p><strong>Straight and Level Flight condition:</strong> Lift = Weight AND Thrust = Drag simultaneously.</p>
        <p><strong>Bernoulli&apos;s Principle:</strong> Air moving over a curved upper wing surface must travel farther than air below. Because it must cover the greater distance in the same time, it moves faster. Faster moving air has lower pressure (Bernoulli). The higher pressure below the wing pushes the wing upward — this is lift. Angle of attack also contributes by deflecting air downward (Newton&apos;s Third Law).</p>
        <p><strong>B-17 weight math:</strong></p>
        <ul className="answer-list">
          <li>Empty weight: ~36,135 lbs. Crew: 10 × 200 lbs = 2,000 lbs. Fuel: 2,780 gallons × 6 lbs/gal = 16,680 lbs. Bombs: 6,000 lbs. Ammo/guns: ~1,000 lbs.</li>
          <li>Total ≈ 61,815 lbs — within the 65,500 lb max.</li>
          <li>Remaining capacity: ≈ 3,685 lbs. Mary Kelley at ~130 lbs fits comfortably.</li>
          <li>After fuel burn on outbound leg (200 gal/hr × 4 hrs = 800 gals = 4,800 lbs burned): Aircraft is approximately 4,800 lbs lighter. This increases climb performance and cruise speed.</li>
        </ul>
        <p><strong>Altitude and temperature:</strong> Standard lapse rate: -3.5°F per 1,000 ft. At 28,000 ft: 59°F − (28 × 3.5°F) = 59°F − 98°F = <strong>−39°F</strong> standard. At altitude the actual temperature over Northern Europe in winter can reach −40°F to −55°F.</p>
        <p><strong>Hypoxia:</strong> Above 10,000 ft, atmospheric pressure is insufficient to force adequate O₂ into the bloodstream without supplemental oxygen. Symptoms: impaired judgment, confusion, tunnel vision, unconsciousness. B-17 crews used oxygen masks above 10,000 ft. A crewman who disconnected his oxygen line could lose consciousness in minutes without realizing it.</p>
      </AnswerKeyBlock>

      <SectionRule />

      {/* ===== WEEK 2 ===== */}
      <ChapterBanner chapter="Week 2" title="Navigation — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Dead Reckoning formula:</strong> Distance = Speed × Time. <br />
          Example: 160 mph ground speed for 3.5 hours = 560 miles. Heading 090° (due east), no wind = position is 560 miles due east of departure point.</p>
        <p><strong>Wind correction math:</strong></p>
        <ul className="answer-list">
          <li>Airspeed 160 mph. Intended heading: 090°. Crosswind from north at 30 mph.</li>
          <li>Drift angle: arctan(30/160) ≈ 10.6°. Apply 10.6° correction into the wind (fly 079°) to maintain track of 090°.</li>
          <li>Ground speed: √(160² + 30²) is wrong — this is a crosswind case. Ground speed ≈ √(160² − 30²) is also simplified. Exact: the ground speed along track = 160 × cos(10.6°) ≈ 157 mph.</li>
        </ul>
        <p><strong>Celestial Navigation:</strong> The sextant measures the angle between a celestial body (sun, star, planet) and the horizon. Combined with precise time (chronometer) and a nautical almanac giving the celestial body&apos;s predicted position, the navigator plots a &ldquo;line of position.&rdquo; Two such lines intersect at the aircraft&apos;s position. Accuracy: within 1-2 miles on a stable aircraft.</p>
        <p><strong>Norden Bombsight:</strong> An analog computer that integrated aircraft speed, altitude, wind, and target data to calculate the exact moment of bomb release. The bombardier entered known data; the sight computed the release point. At 28,000 ft altitude, accuracy was approximately 300 feet CEP under ideal conditions — remarkable for 1944. The bombsight required the bomb run to be flown straight-and-level: any maneuver would invalidate the calculation.</p>
        <p><strong>Eddie and Mary (Ch. 17-18):</strong> They meet at the mission briefing. Eddie notes her yellow-antennae pencils. Their first laugh together — Mary misquotes an altitude and Eddie corrects her. The navigator&apos;s precision and the journalist&apos;s way with words are complementary. Eddie&apos;s core verse (Proverbs 3:5-6) — &ldquo;lean not on your own understanding... He shall direct your paths&rdquo; — is the spiritual equivalent of dead reckoning: trust the One who knows the full route.</p>
      </AnswerKeyBlock>

      <SectionRule />

      {/* ===== WEEK 3 ===== */}
      <ChapterBanner chapter="Week 3" title="Engines — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Four strokes in order:</strong> 1. Intake (piston moves down, air-fuel mixture enters). 2. Compression (piston moves up, mixture compressed). 3. Power/Combustion (spark ignites compressed mixture, expanding gases force piston down). 4. Exhaust (piston moves up, burnt gases expelled).</p>
        <p><strong>Radial vs. Inline:</strong> Radial cylinders are arranged in a circle around the crankshaft. Air cooling is excellent because all cylinders are exposed to airflow. More reliable for high-altitude operations; lighter for the power produced. Inline engines were used in British (Merlin-powered Spitfire/Lancaster) and German aircraft. Radial engines are more visible externally and create more drag but are simpler to maintain in field conditions.</p>
        <p><strong>Feathering math:</strong></p>
        <ul className="answer-list">
          <li>Normal drag (one engine, windmilling propeller): significant drag, asymmetric thrust.</li>
          <li>Feathered (blade edge-on to airflow): drag reduced ~80%. Aircraft can maintain altitude and heading on three engines if not overloaded.</li>
          <li>B-17 could maintain formation altitude on three engines at most weights. On two engines, altitude could not be maintained — crew would have to descend below formation, becoming vulnerable to fighters.</li>
        </ul>
        <p><strong>Fuel math:</strong> Four engines × 50 gal/hr = 200 gal/hr total consumption. Fuel capacity: 2,780 gallons. Maximum endurance: 2,780 ÷ 200 = <strong>13.9 hours</strong>. At 160 mph ground speed: 13.9 × 160 = <strong>2,224 miles maximum range</strong> (no reserves). Operational range with reserves: approximately 1,850 miles (allows 30-minute reserve at altitude + emergency fuel).</p>
        <p><strong>Berlin mission (Ch. 19):</strong> England to Berlin and back is approximately 1,200 miles round trip. At 200 gal/hr, this requires ≈ 1,500 gallons = 54% of total fuel. The crew had sufficient fuel — but battle damage (Ch. 20) may have caused fuel loss, contributing to the decision to bail out over Belgium rather than attempt to return to England.</p>
      </AnswerKeyBlock>

      <SectionRule />

      {/* ===== WEEK 4 ===== */}
      <ChapterBanner chapter="Week 4" title="Radio and Communications — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Electromagnetic Spectrum (low to high frequency):</strong> Radio waves → Microwaves → Infrared → Visible light → Ultraviolet → X-rays → Gamma rays. Radio waves: 3 Hz – 300 GHz. B-17 HF radios: 3-30 MHz. VHF voice communication: 30-300 MHz. Radar: typically 300 MHz – 300 GHz (microwave).</p>
        <p><strong>Morse Code Practice:</strong> SOS = · · · − − − · · ·. &ldquo;Eddie&rdquo; in Morse: E (·) D (− · ·) D (− · ·) I (· ·) E (·) = · − · · − · · · · ·. Grade any correctly transmitted message using standard Morse reference.</p>
        <p><strong>Radio Direction Finding (RDF):</strong> A directional antenna determines the bearing of a signal. Two RDF stations at known locations triangulate the signal source at their bearing intersection. WWII: German Y-Gerät guided their bombers; Allied Loran used synchronized pulses for long-range navigation. Vulnerability: the transmitting aircraft could be located by the enemy using the same technique — radio silence was required on missions unless in emergency.</p>
        <p><strong>Vinny Rosario&apos;s role:</strong> The radio operator maintained communication with base throughout the mission, transmitted position reports, received weather updates and mission changes, and — if the aircraft were going down — transmitted the distress call. On a mission requiring radio silence, Rosario monitored but did not transmit until attack or emergency.</p>
        <p><strong>Mary and Julien (Ch. 27):</strong> Mary sends Donald&apos;s gold World&apos;s Fair necklace to Lee as a recognition token via Julien the resistance courier. This is low-tech communication (physical object as authentication code) that mirrors the principle of all secure communication: both parties must have a shared secret that an interceptor cannot easily duplicate. In modern cryptography this is called a &ldquo;pre-shared key.&rdquo;</p>
      </AnswerKeyBlock>

      <SectionRule />

      {/* ===== WEEK 5 ===== */}
      <ChapterBanner chapter="Week 5" title="Weather and Combat Environment — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Cloud types by altitude:</strong> Low (surface–6,500 ft): Stratus, Stratocumulus, Nimbostratus. Middle (6,500–20,000 ft): Altostratus, Altocumulus. High (above 20,000 ft): Cirrus, Cirrostratus, Cirrocumulus. Vertical (all altitudes): Cumulus, Cumulonimbus. B-17s at 28,000 ft would routinely fly through Cirrus and above most Altostratus. Cumulonimbus should be avoided at all altitudes.</p>
        <p><strong>Wind math — outbound with tailwind:</strong></p>
        <ul className="answer-list">
          <li>Airspeed 160 mph + 40 mph tailwind = <strong>200 mph ground speed</strong> outbound.</li>
          <li>Time to target: 700 ÷ 200 = 3.5 hours (vs. 4.375 hours with no wind). <strong>0.875 hours faster</strong>.</li>
          <li>Return with 40 mph headwind: GS = 120 mph. Time = 700 ÷ 120 = 5.83 hours.</li>
          <li>Extra fuel at 200 gal/hr: (5.83 − 4.375) × 200 = 1.46 hours × 200 = <strong>292 additional gallons</strong> consumed vs. no-wind return.</li>
        </ul>
        <p><strong>Flak time-of-flight math:</strong></p>
        <ul className="answer-list">
          <li>Shell at 2,600 ft/sec to 28,000 ft: 28,000 ÷ 2,600 = <strong>10.77 seconds</strong> (ignoring gravity/drag deceleration — actual is slightly longer, ~12-14 sec).</li>
          <li>B-17 at 160 mph = 234.7 ft/sec. In 10.77 sec: 234.7 × 10.77 = <strong>2,528 feet</strong> traveled. German gunners had to predict where the aircraft would be ≈ 2,500 feet ahead of where they aimed.</li>
        </ul>
        <p><strong>Battle of the Bulge and weather:</strong> December 16-23, 1944 — solid overcast prevented Allied air operations. German planners specifically selected the attack date based on weather forecasts showing sustained low ceilings. When the weather cleared on December 23, Allied tactical air power immediately devastated German armored columns, contributing to the failure of the offensive. Aviation weather is not merely a navigation problem — it is a strategic factor.</p>
      </AnswerKeyBlock>

      <SectionRule />

      {/* ===== WEEK 6 ===== */}
      <ChapterBanner chapter="Week 6" title="Modern Aviation — Answer Key" />
      <AnswerKeyBlock>
        <p><strong>Jet engine and Newton&apos;s Third Law:</strong> The turbine compresses air, adds fuel, combusts the mixture, and expels hot exhaust rearward at high velocity. The reaction to this rearward exhaust is a forward force — thrust. Everyday analogy: a balloon released without tying — the air rushes out the back, the balloon flies forward.</p>
        <p><strong>GPS — satellites needed:</strong> Three satellites determine 2D position (latitude + longitude). A fourth satellite is required to solve for altitude, because the receiver&apos;s clock has its own error that must be solved as a fourth unknown. With only three satellites, the receiver cannot distinguish between &ldquo;I am at this location at 28,000 feet&rdquo; and &ldquo;I am at this location plus a clock error.&rdquo;</p>
        <p><strong>GPS clock precision math:</strong> Speed of light = 186,000 miles/sec = 186 miles/millisecond = 0.186 miles/microsecond. A 1-microsecond clock error = <strong>0.186 miles = 982 feet</strong> of position error. Modern GPS satellites carry atomic clocks accurate to ~1 nanosecond, giving theoretical position accuracy of ~1 foot.</p>
        <p><strong>Final Essay rubric (Week 6, Day 4):</strong> Strong essays include: (1) At least three specific technical facts from the curriculum (e.g., Bernoulli&apos;s Principle, dead reckoning, radial engine four-stroke cycle, flak time-of-flight). (2) At least two specific novel scenes connected to technical concepts (e.g., bomb run requiring straight-and-level = Norden bombsight; snow covering footprints = weather as participant). (3) A thoughtful conclusion connecting the B-17 era to modern aviation beyond mere &ldquo;jets are faster.&rdquo;</p>
        <p><strong>Final Review Math (Week 6, Day 5, Q6):</strong></p>
        <ul className="answer-list">
          <li>Outbound: 700 mi ÷ (160 + 20) = 700 ÷ 180 = 3.89 hrs = 3h 53m. Depart 0630 → arrive target: <strong>1023</strong> (approximately 10:23 AM).</li>
          <li>Return: 700 mi ÷ (160 − 20) = 700 ÷ 140 = 5.0 hrs. Depart target ~1023 (add 30 min time-over-target) → depart 1053 + 5h00m = <strong>1553 (3:53 PM)</strong>.</li>
          <li>Total mission time: approximately 9 hours 23 minutes.</li>
        </ul>
        <p><strong>Jack Gaffney / Crew Chief Legacy:</strong> The Historical Note records that the real Destiny&apos;s Child was on its 53rd mission when shot down on July 20, 1944, targeting Leipzig. Crew chief Jack Gaffney maintained the aircraft through all 53 missions, earning the Bronze Star. This represents what the novel calls &ldquo;the invisible crew&rdquo; — the ground personnel whose work made every flight possible. Modern analogues: the FAA 100-hour inspection, A&amp;P certification, and the avionics technician&apos;s work before every departure.</p>
      </AnswerKeyBlock>

    </div>
  );
}