import CoverPage from "@/components/workbook/CoverPage";
import WeekBanner from "@/components/workbook/WeekBanner";
import DayCard from "@/components/workbook/DayCard";
import ShortAnswer from "@/components/workbook/ShortAnswer";
import EssayBox from "@/components/workbook/EssayBox";
import SidebarBox from "@/components/workbook/SidebarBox";
import VocabCard from "@/components/workbook/VocabCard";
import VocabGrid from "@/components/workbook/VocabGrid";
import MapBox from "@/components/workbook/MapBox";
import FillBlank from "@/components/workbook/FillBlank";
import SectionRule from "@/components/workbook/SectionRule";
import PrintButton from "@/components/PrintButton";

export default function AvionicsPage() {
  return (
    <div className="workbook-body">
      <PrintButton />

      <CoverPage
        series="Arms of Deliverance Learning Series"
        title="Six-Week Introduction to Avionics"
        subtitle="How Eddie Anderson Found His Way Home — Navigation, Aircraft Systems, and the Science of Flight"
        author="Tricia Goyer"
        description="35-40 minutes per day · Grades 6-12 · No prior science required"
      />

      <SectionRule />

      {/* =========================================== */}
      {/* WEEK 1 — THE B-17 AND THE SCIENCE OF FLIGHT */}
      {/* =========================================== */}
      <section className="print-unit">
      <WeekBanner
        week={1}
        title="The B-17 Flying Fortress — Anatomy of a Warbird"
        subtitle="How a 65,000-pound aircraft leaves the ground"
        color="blue"
      />

      <DayCard day={1} week={1} title="Meet Destiny's Child">
        <SidebarBox title="From the Novel (Ch. 17-18)">
          On the morning of his 30th and final mission, Eddie Anderson crawled into the nose of
          the B-17 called Destiny's Child. The crew called their aircraft home — a flying aluminum
          tube that would carry ten men to 28,000 feet above Germany while enemy fighters and
          anti-aircraft guns tried to kill them. The aircraft flew on four Wright R-1820 Cyclone
          radial engines, each producing 1,200 horsepower. A full fuel load weighed 3,630 pounds
          per tank — four tanks, two per wing. Eddie's job was to tell this machine exactly where
          to go.
        </SidebarBox>
        <VocabGrid>
          <VocabCard term="Fuselage" definition="The main body of an aircraft — the tube that houses the crew, fuel, and bombs." />
          <VocabCard term="Wing" definition="The aerodynamic surface that generates lift. B-17 wingspan was 103 feet, 9 inches." />
          <VocabCard term="Empennage" definition="The tail section of an aircraft — includes the vertical stabilizer, horizontal stabilizer, rudder, and elevators." />
          <VocabCard term="Propeller" definition="A rotating airfoil that converts engine power into thrust." />
          <VocabCard term="Radial Engine" definition="A type of internal combustion engine with cylinders arranged in a circle around the crankshaft. The B-17 used four Wright R-1820 Cyclone radial engines." />
        </VocabGrid>
        <ShortAnswer question="1. Name the four main structural components of an aircraft." lines={2} />
        <ShortAnswer question="2. How many engines did the B-17 have? How many could it lose and still fly home? (Hint: Ch. 5)" lines={2} />
        <ShortAnswer question="3. Why do you think the nose section (where Eddie sat) was made of Plexiglas rather than aluminum?" lines={3} />
        <MapBox label="Draw a B-17 and label: fuselage, wings, empennage, engines (4), nose section, cockpit, bomb bay, tail" height="220px" />
      </DayCard>

      <DayCard day={2} week={1} title="The Four Forces of Flight">
        <p className="lesson-text">
          Every aircraft — from the Wright Flyer to the B-17 — is governed by four competing
          forces: <strong>Lift</strong> (up), <strong>Weight / Gravity</strong> (down),
          <strong> Thrust</strong> (forward), and <strong>Drag</strong> (backward). When lift
          exceeds weight, the plane climbs. When thrust exceeds drag, the plane accelerates.
          The B-17 at takeoff generated enough lift to hoist 65,500 pounds off the runway.
        </p>
        <VocabGrid>
          <VocabCard term="Lift" definition="The upward force created by airflow over and under a wing. Generated by wing shape (airfoil) and angle of attack." />
          <VocabCard term="Drag" definition="Air resistance — the force that opposes an aircraft's forward motion." />
          <VocabCard term="Thrust" definition="The forward force produced by the engines and propellers." />
          <VocabCard term="Weight" definition="The downward force of gravity acting on the aircraft and everything inside it." />
          <VocabCard term="Airfoil" definition="A shape designed to generate lift when air flows over it. The cross-section of a wing is an airfoil." />
          <VocabCard term="Angle of Attack" definition="The angle between the wing's chord line and the incoming airflow. Increases lift up to a critical point (stall)." />
        </VocabGrid>
        <ShortAnswer question="1. Draw a simple aircraft and label the four forces with arrows showing their direction." lines={7} />
        <ShortAnswer question="2. What happens when drag exceeds thrust? Apply this to a B-17 climbing toward 28,000 feet — how does this explain why the engines work so hard at altitude?" />
        <ShortAnswer question="3. In Chapter 5, Destiny's Child flew home on three of its four engines after losing one to enemy fire. Using the four forces, explain why losing one engine makes the flight more difficult but not impossible." />
      </DayCard>

      <DayCard day={3} week={1} title="Bernoulli's Principle — Why Wings Work">
        <p className="lesson-text">
          A wing works because of <strong>Bernoulli's Principle</strong>: as the speed of a
          fluid (including air) increases, its pressure decreases. A wing's upper surface is
          curved, causing air to travel faster over the top than the bottom. This faster-moving
          air creates lower pressure above the wing. The higher pressure below pushes the wing
          upward — creating lift.
        </p>
        <ShortAnswer question="1. State Bernoulli's Principle in your own words." lines={3} />
        <ShortAnswer question="2. Why is the upper surface of a wing curved while the lower surface is flatter? What effect does this shape have on airflow?" />
        <ShortAnswer question="3. Simple experiment: Hold a piece of paper just below your lip and blow across the top of it. The paper should rise. Explain this using Bernoulli's Principle." />
        <ShortAnswer question="4. The B-17's wingspan was 103 feet, 9 inches. Why do you think larger wings generate more lift?" lines={2} />
      </DayCard>

      <DayCard day={4} week={1} title="Atmosphere and Altitude">
        <p className="lesson-text">
          B-17s flew their missions between 20,000 and 30,000 feet. At altitude, two things
          happen that make flight progressively harder: air pressure drops (less dense air means
          less oxygen for engines and crew), and temperature plummets. In Chapter 18, Mary
          is told the temperature at Destiny's Child's bombing altitude would be <strong>-55°F</strong>.
          Without electric heating suits, a crew member's blood would begin to freeze in the veins.
        </p>
        <VocabGrid>
          <VocabCard term="Troposphere" definition="The lowest layer of Earth's atmosphere, from sea level to about 7 miles up. Most weather occurs here; B-17 missions operated in this layer." />
          <VocabCard term="Air Pressure" definition="The weight of the atmosphere pressing down. Decreases with altitude — at 28,000 feet, pressure is about 1/3 of sea level pressure." />
          <VocabCard term="Hypoxia" definition="Oxygen deprivation due to reduced air pressure at altitude. Without supplemental oxygen, pilots lose consciousness above 15,000-20,000 feet." />
          <VocabCard term="Oxygen Mask" definition="Required above 15,000 feet on WWII-era aircraft. Delivered pressurized oxygen directly to the crew member's airway." />
        </VocabGrid>
        <ShortAnswer question="1. Why does air pressure decrease with altitude? What does this tell us about the relationship between weight and pressure?" />
        <ShortAnswer question="2. The B-17 crew wore oxygen masks above 15,000 feet. What medical condition were they preventing? Describe the symptoms of hypoxia." />
        <ShortAnswer question="3. Calculate: If the crew took off at 60°F at sea level and the temperature dropped approximately 3.5°F per 1,000 feet of climb, what would the temperature be at 28,000 feet? Show your work." lines={4} />
        <ShortAnswer question="4. How did the B-17 crew manage the -55°F temperatures described in Chapter 18? Name as many methods as you can find from the text." />
      </DayCard>

      <DayCard day={5} week={1} title="Review — Aircraft Anatomy and Basic Flight">
        <ShortAnswer question="1. List and define the four forces of flight." lines={5} />
        <ShortAnswer question="2. Explain Bernoulli's Principle and describe how it generates lift on a wing." lines={4} />
        <ShortAnswer question="3. Why must B-17 crews use oxygen masks above 15,000 feet? Name the condition they are preventing." lines={2} />
        <ShortAnswer question="4. The B-17's four engines each produced 1,200 hp. Total horsepower = _______. At cruise, they burned approximately 200 gallons of fuel per hour. For a 9-hour mission, how many gallons of fuel would the aircraft need? Show your work." lines={4} />
      </DayCard>

      <SectionRule />

      {/* =========================================== */}
      {/* WEEK 2 — NAVIGATION: FINDING TRUE NORTH */}
      {/* =========================================== */}
      </section>

      <section className="print-unit">
      <WeekBanner
        week={2}
        title="Navigation — Finding True North"
        subtitle="Dead Reckoning, Celestial Navigation, and the Art of Knowing Where You Are"
        color="blue"
      />

      <DayCard day={1} week={2} title="What Is Navigation?">
        <SidebarBox title="Eddie's Job (Ch. 17-19)">
          Eddie Anderson was a navigator — the crew member responsible for knowing exactly where
          Destiny's Child was at every moment of the flight. In 1944, there was no GPS, no radar
          guidance to the target. Navigation depended on: 1) the navigator's calculations about
          speed, heading, and wind drift; 2) a sextant for celestial navigation; 3) a drift meter
          to measure crosswind correction; and 4) visual landmarks when clouds permitted. Eddie
          told Mary: "A navigator finds the way. He doesn't plan the mission; he doesn't fly the
          plane. He just has to keep track of true north."
        </SidebarBox>
        <VocabGrid>
          <VocabCard term="Dead Reckoning" definition="Calculating current position using a known starting point, speed, direction, and elapsed time — without external reference points." />
          <VocabCard term="True North" definition="The direction of the geographic North Pole, as opposed to Magnetic North (where the compass points). Navigators correct for the difference (called magnetic declination)." />
          <VocabCard term="Heading" definition="The direction an aircraft is pointed, measured in degrees (0° = North, 90° = East, 180° = South, 270° = West)." />
          <VocabCard term="Magnetic Declination" definition="The angular difference between True North and Magnetic North. Varies by location and must be corrected in navigation." />
          <VocabCard term="Airspeed vs. Ground Speed" definition="Airspeed: speed relative to the air. Ground speed: speed relative to the ground. Crosswinds create a difference between the two." />
        </VocabGrid>
        <ShortAnswer question="1. What specific tools did a WWII B-17 navigator use to determine position? List as many as you can." />
        <ShortAnswer question="2. Explain dead reckoning in your own words. What are its limitations?" />
        <ShortAnswer question="3. Eddie describes his job as keeping track of 'true north.' What is the difference between True North and Magnetic North?" />
      </DayCard>

      <DayCard day={2} week={2} title="Dead Reckoning Math">
        <p className="lesson-text">
          Dead reckoning (DR) uses three inputs: <strong>speed</strong>, <strong>time</strong>,
          and <strong>heading</strong> to calculate position. If you know where you started, how
          fast you are going, the direction you are flying, and how long you have been flying —
          you can calculate where you are now. The formula is: <br />
          <strong>Distance = Speed × Time</strong>
        </p>
        <ShortAnswer question="1. Destiny's Child cruised at approximately 160 mph at altitude. If Eddie's flight from England to Berlin took about 4.5 hours one way, how many miles is the round trip? Show all math." lines={5} />
        <ShortAnswer question="2. The crew is flying a heading of 090° (East). After 2 hours at 160 mph, they turn to a heading of 180° (South). After 1 hour, where are they relative to their start point? Draw a diagram." lines={7} />
        <ShortAnswer question="3. A crosswind from the north at 30 mph pushes the aircraft south while it is flying east. If the aircraft's compass heading is 090° but the actual track over the ground curves south, what correction would the navigator apply to compensate? (A drawing will help.)" lines={5} />
        <ShortAnswer question="4. Why was navigational precision so critical on a mission to Berlin? What would happen if Eddie miscalculated by just a few degrees over a 4-hour flight?" />
      </DayCard>

      <DayCard day={3} week={2} title="Celestial Navigation — Navigating by the Stars">
        <p className="lesson-text">
          Before GPS, sailors and airmen navigated using the sun, moon, and stars. A WWII
          navigator used a <strong>sextant</strong> — an optical instrument that measures the
          angle between a celestial body (sun or star) and the horizon. Combined with precise
          time (from a chronometer) and printed <em>celestial navigation tables</em>, the
          navigator could calculate latitude and longitude anywhere on Earth.
        </p>
        <VocabGrid>
          <VocabCard term="Sextant" definition="A precision optical instrument used to measure the angle of a celestial body above the horizon, enabling calculation of the observer's geographic position." />
          <VocabCard term="Zenith" definition="The point in the sky directly overhead. The higher a star is in the sky, the closer you are to being directly below it." />
          <VocabCard term="Latitude" definition="Angular distance north or south of the equator, measured in degrees. Polaris (the North Star) appears at an angle equal to your latitude." />
          <VocabCard term="Longitude" definition="Angular distance east or west of the prime meridian (Greenwich, England). Determined by comparing local time to Greenwich Mean Time (GMT)." />
          <VocabCard term="Chronometer" definition="A highly accurate clock used in navigation. Knowing precise Greenwich Mean Time is essential for longitude calculation." />
        </VocabGrid>
        <ShortAnswer question="1. Why is accurate timekeeping essential for celestial navigation? What does time have to do with longitude?" />
        <ShortAnswer question="2. If Polaris (the North Star) appears 52° above your horizon, what is your approximate latitude?" lines={2} />
        <ShortAnswer question="3. B-17s flew above the clouds on many missions. Why might this create a problem for celestial navigation? What alternative methods would a navigator use?" />
        <MapBox label="Practice: On this blank map of Europe, mark the approximate latitude and longitude of: Bassingbourn, England / Brussels, Belgium / Berlin, Germany" height="230px" />
      </DayCard>

      <DayCard day={4} week={2} title="Radio Navigation and the Norden Bombsight">
        <SidebarBox title="The Norden Bombsight">
          The Norden bombsight was a top-secret optical and mechanical computer that allowed the
          bombardier to calculate the exact moment to release bombs to hit a specific target on
          the ground, accounting for the aircraft's altitude, airspeed, wind drift, and angle of
          approach. American crews were so protective of the Norden that they were ordered to
          destroy it with a fire ax if the aircraft went down. The Army Air Forces claimed the
          Norden could 'drop a bomb in a pickle barrel from 20,000 feet.' In reality, under
          combat conditions, accuracy was far harder — especially when the IP (Initial Point)
          required straight-and-level flight through concentrated flak.
        </SidebarBox>
        <ShortAnswer question="1. What variables did the Norden bombsight have to calculate to determine the correct bomb release point?" />
        <ShortAnswer question="2. Why were crews ordered to destroy the Norden bombsight if forced to bail out or crash-land in enemy territory?" />
        <ShortAnswer question="3. In Chapters 19-20, the bomb run over Berlin requires Eddie's aircraft to fly straight and level from the IP to the target. Using what you know about the four forces of flight and navigation, explain why this straight-and-level requirement was so dangerous." />
        <ShortAnswer question="4. Modern aircraft use GPS for navigation. What advantages does GPS have over dead reckoning and celestial navigation? What might be a potential vulnerability?" lines={3} />
      </DayCard>

      <DayCard day={5} week={2} title="Review — Navigation">
        <ShortAnswer question="1. What is dead reckoning? List its three inputs." lines={3} />
        <ShortAnswer question="2. Destiny's Child flew from England to Berlin on a heading of approximately 105° (East-Southeast) at 160 mph. If the flight to target took 4 hours 20 minutes, calculate the approximate one-way distance. Show your work." lines={5} />
        <ShortAnswer question="3. Explain the difference between True North and Magnetic North. Why does it matter for a bomber mission?" lines={3} />
        <ShortAnswer question="4. How does the Norden bombsight connect navigation to the bombing mission?" lines={3} />
        <ShortAnswer question="5. Eddie says a navigator 'keeps track of true north' as a metaphor for his faith. In one paragraph, explain this metaphor and whether you think it is effective." lines={5} />
      </DayCard>

      <SectionRule />
      {/* =========================================== */}
      {/* WEEK 3 — ENGINES AND PROPULSION */}
      {/* =========================================== */}
      </section>

      <section className="print-unit">
      <WeekBanner
        week={3}
        title="Engines and Propulsion — What Makes a 65,000-lb Warbird Fly"
        subtitle="Internal combustion, superchargers, and keeping the power on"
        color="blue"
      />

      <DayCard day={1} week={3} title="The Wright R-1820 Cyclone Engine">
        <SidebarBox title="B-17 Engine Facts">
          The B-17G Flying Fortress was powered by four Wright R-1820-97 Cyclone 9 radial
          engines. Each engine had nine cylinders arranged in a circle. Each cylinder displaced
          182 cubic inches. Total displacement per engine: 1,820 cubic inches (hence 'R-1820').
          At full war emergency power, each engine produced 1,380 horsepower. Combined, the four
          engines generated 5,520 hp — enough to lift 65,500 lbs and cruise at 182 mph at
          25,000 feet. Because of the thin air at altitude, each engine was equipped with a
          turbocharger to maintain power.
        </SidebarBox>
        <VocabGrid>
          <VocabCard term="Radial Engine" definition="An engine whose cylinders are arranged in a circle around the crankshaft, like spokes of a wheel. Air-cooled; reliable and powerful." />
          <VocabCard term="Displacement" definition="The total volume swept by all the pistons in an engine during one complete cycle, measured in cubic inches or liters. Larger displacement = more potential power." />
          <VocabCard term="Horsepower (hp)" definition="A unit of power. One horsepower = the ability to lift 550 pounds one foot in one second. Named by James Watt." />
          <VocabCard term="Turbocharger" definition="A turbine-driven device that compresses intake air before it enters the engine, restoring power lost at high altitudes where air is thin." />
          <VocabCard term="Manifold Pressure" definition="The pressure of the air-fuel mixture entering the engine cylinders. Higher MP = more power. Monitored carefully by the engineer." />
        </VocabGrid>
        <ShortAnswer question="1. Why did the B-17's engines need turbochargers? What happens to engine power at 28,000 feet without one?" />
        <ShortAnswer question="2. Calculate: If one R-1820 engine produces 1,200 hp at normal rated power and the B-17 has four engines, what is the total horsepower? If one engine fails, what percentage of total power is lost?" lines={4} />
        <ShortAnswer question="3. A radial engine is air-cooled (unlike a car engine, which is water-cooled). What are the advantages of air cooling for a WWII bomber? What are the disadvantages?" />
      </DayCard>

      <DayCard day={2} week={3} title="The Four-Stroke Cycle — How an Engine Makes Power">
        <p className="lesson-text">
          All piston engines — from your family car to the Wright R-1820 — work on the same
          four-stroke cycle: <strong>Intake → Compression → Power → Exhaust</strong> (sometimes
          remembered as "Suck, Squeeze, Bang, Blow"). Understanding this cycle helps explain
          everything from fuel requirements to engine failure under fire.
        </p>
        <ShortAnswer question="1. Describe each of the four strokes in your own words. Draw a diagram showing piston position during each stroke." lines={10} />
        <ShortAnswer question="2. During the compression stroke, what happens to the air-fuel mixture? Why does squeezing the mixture before igniting it produce more power?" lines={3} />
        <ShortAnswer question="3. Aviation fuel (100LL avgas) has a higher octane rating than car gasoline. What does octane rating measure, and why is a higher rating important in a high-compression aircraft engine?" />
        <ShortAnswer question="4. In Chapter 5, Destiny's Child lost one engine to enemy fire and flew home on three. At what stroke in the cycle might enemy fire cause an engine to fail? Give at least two possible scenarios." />
      </DayCard>

      <DayCard day={3} week={3} title="Propellers — Converting Power into Thrust">
        <p className="lesson-text">
          A propeller is a rotating airfoil — it works exactly like a wing, except instead of
          generating lift upward, it generates lift (thrust) forward. Each blade is twisted
          along its length so that every part of the blade travels at the same angle of attack
          relative to the air, regardless of whether it is near the hub (slower) or the tip
          (faster). Variable-pitch propellers allow the pilot to change the blade angle to
          optimize efficiency at different speeds and altitudes.
        </p>
        <VocabGrid>
          <VocabCard term="Pitch (propeller)" definition="The angle of a propeller blade relative to its plane of rotation. High pitch = more thrust per revolution at high speed. Low pitch = easier engine starting and low-speed operation." />
          <VocabCard term="RPM (Revolutions Per Minute)" definition="How fast the engine and propeller are turning. The engineer monitors RPM as a measure of engine health." />
          <VocabCard term="Feathering" definition="Rotating propeller blades to align with the airstream (edge-on) when an engine fails. Reduces drag from the dead engine." />
          <VocabCard term="Torque" definition="The rotational force produced by the engine. All four B-17 propellers rotated in the same direction, creating a pulling torque that the pilots had to counteract with rudder." />
        </VocabGrid>
        <ShortAnswer question="1. Explain why a propeller is an airfoil. How does Bernoulli's Principle apply to a spinning propeller blade?" />
        <ShortAnswer question="2. When Destiny's Child lost an engine in Chapter 5, the engineer would have feathered that propeller. Why? What would happen if he did not feather it?" />
        <ShortAnswer question="3. Why is the tip of a propeller blade twisted differently than the root? Use the concept of velocity to explain." />
      </DayCard>

      <DayCard day={4} week={3} title="Fuel Systems and Fuel Load">
        <p className="lesson-text">
          The B-17G carried up to 2,810 gallons of 100-octane aviation gasoline in self-sealing
          fuel tanks built into the wings. 'Self-sealing' meant the tanks were lined with a rubber
          compound that swelled when pierced by a bullet, slowing or stopping the fuel leak and
          reducing fire risk. At cruise power, the four R-1820 engines consumed approximately
          200 gallons per hour combined.
        </p>
        <ShortAnswer question="1. Calculate: If Destiny's Child carries 2,810 gallons and burns 200 gallons/hour, what is the maximum theoretical range in hours? In miles at 160 mph cruise speed?" lines={5} />
        <ShortAnswer question="2. Why did bomber crews have to carefully plan their fuel load for each specific mission? What happens if they run out of fuel over the Channel?" lines={3} />
        <ShortAnswer question="3. Explain how a self-sealing fuel tank works. Why was this an important innovation for a combat aircraft?" />
        <ShortAnswer question="4. As a bomber drops bombs, it becomes lighter. Using the four forces of flight, describe what happens to the aircraft when the bomb load (up to 8,000 lbs) is released." />
      </DayCard>

      <DayCard day={5} week={3} title="Review — Engines and Propulsion">
        <ShortAnswer question="1. What type of engine powered the B-17? Name the specific model." lines={2} />
        <ShortAnswer question="2. Explain the four-stroke cycle from memory." lines={4} />
        <ShortAnswer question="3. What is feathering a propeller, and when would a crew do it?" lines={3} />
        <ShortAnswer question="4. Math problem: A B-17 on a 9-hour Berlin mission (4.5 hrs each way) burns 200 gallons/hour. How many gallons total? If each gallon weighs 6 pounds, how many pounds of fuel does it burn on this mission? Show work." lines={6} />
      </DayCard>

      <SectionRule />

      {/* =========================================== */}
      {/* WEEK 4 — COMMUNICATIONS AND RADIO SYSTEMS */}
      {/* =========================================== */}
      </section>

      <section className="print-unit">
      <WeekBanner
        week={4}
        title="Radio — Communication Under Fire"
        subtitle="How Vinny Rosario kept Destiny's Child talking to the world"
        color="blue"
      />

      <DayCard day={1} week={4} title="The Radio Operator's World">
        <SidebarBox title="Vinny Rosario — Radio Operator">
          Sergeant Vinny Rosario was the radio operator aboard Destiny's Child. The radio
          operator's station sat amidships in the fuselage above the bomb bay. Vinny operated
          the SCR-287 high-frequency radio set — used for long-range communication with base
          — and assisted with navigation by using radio direction finding (DF). He also operated
          the interphone system that connected all ten crew positions. When the aircraft was
          shot down, the last transmission Vinny could send was a brevity code: his position,
          altitude, and the word 'bailout.' That transmission, monitored by friendly forces,
          was how the crew's survival was confirmed.
        </SidebarBox>
        <VocabGrid>
          <VocabCard term="Radio Wave" definition="An electromagnetic wave at frequencies used for wireless communication. Travels at the speed of light (186,000 miles per second)." />
          <VocabCard term="Frequency" definition="The number of wave cycles per second, measured in Hertz (Hz). Higher frequency = shorter wavelength. AM radio: 540-1700 kHz. Aircraft HF: 2-30 MHz." />
          <VocabCard term="Amplitude Modulation (AM)" definition="A method of encoding audio onto a radio carrier wave by varying the wave's amplitude (strength). Used in WWII aircraft HF communication." />
          <VocabCard term="Morse Code" definition="A communication system using dots and dashes (short and long signals) to represent letters and numbers. WWII radiomen trained to send and receive 18-20 words per minute." />
          <VocabCard term="Interphone" definition="The internal communications system connecting all crew positions on the aircraft, using the aircraft's electrical system and crew headsets." />
        </VocabGrid>
        <ShortAnswer question="1. What is a radio wave? How does it travel from the aircraft's antenna to a receiver on the ground?" lines={3} />
        <ShortAnswer question="2. Why would a B-17 crew use Morse code rather than voice communication for critical navigational information?" />
        <ShortAnswer question="3. When Destiny's Child was shot down (Ch. 20), Vinny's last transmission was the crew's position and the word 'bailout.' Why was this transmission important — what happened because of it?" />
      </DayCard>

      <DayCard day={2} week={4} title="The Electromagnetic Spectrum">
        <p className="lesson-text">
          Radio waves are part of the electromagnetic spectrum — a continuum of waves that
          includes (from longest to shortest wavelength): radio waves, microwaves, infrared,
          visible light, ultraviolet, X-rays, and gamma rays. All travel at the speed of light.
          Different frequencies of radio waves behave differently: high-frequency (HF) waves
          can bounce off the ionosphere and travel thousands of miles; very high frequency
          (VHF) and ultra high frequency (UHF) waves travel in straight lines and are used
          for short-range communication.
        </p>
        <ShortAnswer question="1. List the bands of the electromagnetic spectrum in order from longest to shortest wavelength." lines={3} />
        <ShortAnswer question="2. Why can AM radio stations be received hundreds of miles away at night, but only a few dozen miles during the day? (Hint: ionosphere)" lines={3} />
        <ShortAnswer question="3. Modern aircraft use VHF (118-136 MHz) for air traffic control. WWII bombers used HF (2-30 MHz) for long-range communication. What is the difference, and why does each frequency range have the range characteristics it does?" />
        <ShortAnswer question="4. Radar (Radio Detection And Ranging) uses UHF and microwave frequencies. How does radar work? How did the Pathfinder Aircraft use radar to bomb through clouds? (Reference Ch. 9 and your knowledge of em waves.)" />
      </DayCard>

      <DayCard day={3} week={4} title="Morse Code and Coding">
        <p className="lesson-text">
          Samuel Morse invented Morse code in 1838. Each letter of the alphabet is represented
          by a unique combination of short signals (dots) and long signals (dashes). The most
          famous Morse code signal is <strong>SOS: · · · — — — · · ·</strong> (three dots,
          three dashes, three dots). A skilled WWII radio operator could send and receive
          18-20 words per minute by ear.
        </p>
        <ShortAnswer question="1. Practice: Using a Morse code chart, decode this message: ·— — — — — ·· ·· ··· / · — · · ·· ·— ···· ·— ·—· · (Answer in the answer key)" lines={3} />
        <ShortAnswer question="2. Why was Morse code still used by WWII radio operators when voice radio was available? List at least two advantages of Morse code over voice." />
        <ShortAnswer question="3. Encode your full name in Morse code." lines={4} />
        <ShortAnswer question="4. Modern digital communications use binary code (1s and 0s) instead of dots and dashes. How are binary code and Morse code conceptually similar?" />
      </DayCard>

      <DayCard day={4} week={4} title="Radio Direction Finding and Navigation">
        <p className="lesson-text">
          Before GPS, aircraft navigators used <strong>Radio Direction Finding (RDF)</strong>
          to locate their position. By tuning a directional antenna to a known radio beacon
          and rotating the antenna until the signal was at maximum strength, the navigator
          could determine the <strong>bearing</strong> (compass direction) to that beacon. By
          taking bearings to two or more beacons and plotting the intersecting lines on a map,
          the navigator could fix his position. This technique is called <strong>triangulation</strong>.
        </p>
        <VocabGrid>
          <VocabCard term="Bearing" definition="The compass direction from the aircraft to a fixed point (beacon, landmark, radio station), measured in degrees." />
          <VocabCard term="Radio Beacon" definition="A transmitter at a known location that broadcasts a continuous signal, allowing aircraft to take a bearing toward it." />
          <VocabCard term="Triangulation" definition="Determining position by taking bearings to two or more known points and finding where the bearing lines intersect." />
          <VocabCard term="Position Fix" definition="A confirmed location for the aircraft based on triangulation or visual identification of a landmark." />
        </VocabGrid>
        <ShortAnswer question="1. Explain triangulation in your own words. Draw a simple diagram showing how to find a position using bearings to two radio beacons." lines={8} />
        <ShortAnswer question="2. Why did navigators need both dead reckoning AND radio direction finding? What does each method do that the other cannot?" />
        <ShortAnswer question="3. In Chapter 20, Eddie lands in Belgian farmland after bailing out. His first priority is to inventory his escape kit. His compass is one item. How would he use it with the sun's position to determine which direction to travel?" />
      </DayCard>

      <DayCard day={5} week={4} title="Review — Radio and Communications">
        <ShortAnswer question="1. What is a radio wave? Name two factors that determine how far a radio wave travels." lines={3} />
        <ShortAnswer question="2. Explain triangulation using radio direction finding." lines={4} />
        <ShortAnswer question="3. What advantages does Morse code have over voice communication at long range?" lines={3} />
        <ShortAnswer question="4. Decode: ·— ·· · ·· ·—· / — · ·— · (one word — see answer key)" lines={3} />
        <ShortAnswer question="5. How did Vinny Rosario's final transmission after the shoot-down help Eddie and Mary — even though they were already on the ground?" />
      </DayCard>

      <SectionRule />
      {/* =========================================== */}
      {/* WEEK 5 — WEATHER AND AEROMETEROLOGY */}
      {/* =========================================== */}
      </section>

      <section className="print-unit">
      <WeekBanner
        week={5}
        title="Weather — Flying Through the European Winter"
        subtitle="Clouds, icing, flak, and the forecaster's art"
        color="blue"
      />

      <DayCard day={1} week={5} title="WWII European Weather — The Navigator's Enemy">
        <SidebarBox title="Weather and the Novel">
          Winter 1944-1945 in Belgium and Germany was brutal — one of the coldest in decades.
          The Battle of the Bulge (December 1944) was partly enabled by solid cloud cover that
          grounded Allied aircraft for the first critical days of the German offensive, preventing
          ground support. In the novel, Eddie and Mary escape through snow-covered Belgian fields
          after their bailout. Roger the Belgian farmer hides them under quilts in a cold barn.
          German soldiers return to search — and the frozen ground bears no footprints, because
          fresh snow has fallen and covered their tracks. Weather, in this novel, is not
          background — it is a participant.
        </SidebarBox>
        <VocabGrid>
          <VocabCard term="Frontal System" definition="A boundary between two air masses of different temperature and moisture. Cold fronts bring rapid storms; warm fronts bring prolonged cloudiness and rain." />
          <VocabCard term="Cumulonimbus" definition="The towering storm cloud — can extend from 1,000 to 60,000 feet. Contains severe turbulence, hail, lightning, and extreme icing. B-17 crews avoided these when possible." />
          <VocabCard term="Icing" definition="The formation of ice on aircraft surfaces and engine air intakes. Destroys the airfoil shape of wings, adds weight, and blocks engine airflow. Can be fatal." />
          <VocabCard term="Turbulence" definition="Irregular and unpredictable air motion caused by heat currents, wind shear, or storm cells. Severe turbulence can structurally damage aircraft." />
          <VocabCard term="Ceiling" definition="The height above ground of the lowest layer of clouds covering more than half the sky. Low ceiling = poor visibility for visual navigation." />
        </VocabGrid>
        <ShortAnswer question="1. Why was low cloud ceiling a problem for B-17 missions that used visual bombing? How did the Pathfinder aircraft solve this problem?" />
        <ShortAnswer question="2. In Chapter 28, the Battle of the Bulge is partly possible because of cloud cover grounding Allied aircraft. Explain how weather became a strategic factor in one of the war's most significant battles." />
        <ShortAnswer question="3. Aircraft icing is dangerous for two reasons: it destroys the airfoil shape AND adds weight. Using the four forces of flight, explain specifically how these two effects can together cause a crash." />
      </DayCard>

      <DayCard day={2} week={5} title="Clouds and Cloud Types">
        <p className="lesson-text">
          Clouds are classified by both altitude and shape. The three shape types are:
          <strong> Cumulus</strong> (heaped, puffy), <strong>Stratus</strong> (layered, flat),
          and <strong>Cirrus</strong> (high, wispy, made of ice crystals). These combine with
          altitude prefixes: <strong>Alto-</strong> (middle altitude), <strong>Cirro-</strong>
          (high altitude), and for tall clouds: <strong>Cumulonimbus</strong> (thunderstorm).
        </p>
        <ShortAnswer question="1. Draw and label a cloud chart showing at least 8 cloud types at their correct altitudes. Include the altitude range for each." lines={12} />
        <ShortAnswer question="2. B-17s cruised above 20,000 feet. Which cloud types would they routinely fly through? Which cloud type should pilots at any altitude avoid, and why?" />
        <ShortAnswer question="3. The Swiss Alps are visible below Eddie's aircraft near the target in Chapter 19 through breaks in the clouds. At 28,000 feet, the Alps appear below them. The tallest Alpine peak (Mont Blanc) is 15,781 feet. Why is seeing the Alps a useful visual navigation fix for Eddie?" />
      </DayCard>

      <DayCard day={3} week={5} title="Wind — The Invisible Enemy (and Friend)">
        <p className="lesson-text">
          Wind profoundly affects aircraft navigation. A tailwind adds to ground speed; a
          headwind reduces it. A crosswind pushes the aircraft off its intended track. WWII
          navigators broadcast wind observations their upper atmospheric wind measurements to base,
          and meteorologists compiled forecast charts to help mission planners. Getting the wind
          forecast wrong by 30 mph over a 4-hour flight could mean arriving at the target many
          miles off course.
        </p>
        <ShortAnswer question="1. If Destiny's Child is flying east at 160 mph airspeed with a 40 mph tailwind, what is its ground speed? How much faster does it arrive at the target compared to no wind?" lines={4} />
        <ShortAnswer question="2. On the return leg, that same 40 mph wind is now a headwind. What is the ground speed? How much extra fuel does the crew burn compared to no wind? (Burn rate 200 gal/hr)" lines={5} />
        <ShortAnswer question="3. Mary listens in on the German soldiers' truck conversation (Ch. 26). The soldiers mention the attack on St. Vith 'in two days.' She passes this intelligence to Julien. How does this scene illustrate the principle that information you gathered unexpectedly can change the outcome of a battle — just like an unexpected wind can change the outcome of a mission?" />
      </DayCard>

      <DayCard day={4} week={5} title="Anti-Aircraft Fire — The Physics of Flak">
        <p className="lesson-text">
          The German Flugabwehrkanone — anti-aircraft cannon, abbreviated <strong>Flak</strong>
          — was the B-17's most constant threat. The 88mm Flak cannon could fire a 20-pound
          shell to 35,000 feet, where it would burst into hundreds of steel fragments. Berlin
          alone was defended by more than 750 such guns. The physics of flak: the shell was
          time-fused to detonate at a specific altitude. Because a B-17 was moving at 160 mph,
          the gunners had to calculate not where the plane <em>was</em>, but where it
          <em> would be</em> when the shell arrived.
        </p>
        <VocabGrid>
          <VocabCard term="Muzzle Velocity" definition="The speed of a shell as it leaves the barrel of a gun — for the 88mm: approximately 2,600 feet per second." />
          <VocabCard term="Time Fuse" definition="A fuse that detonates the shell after a preset time delay, targeting a specific altitude rather than impact." />
          <VocabCard term="Ballistic Trajectory" definition="The curved path a projectile follows under the influence of gravity and air resistance after it leaves the barrel." />
          <VocabCard term="Evasive Action" definition="Changes in course, speed, or altitude to avoid anti-aircraft fire. Forbidden during the bomb run (IP to target) to ensure accuracy." />
        </VocabGrid>
        <ShortAnswer question="1. If a B-17 is flying at 28,000 feet at 160 mph and an 88mm shell has a muzzle velocity of 2,600 ft/sec, approximately how many seconds does it take the shell to reach the aircraft? How far has the aircraft moved in that time? Show math." lines={6} />
        <ShortAnswer question="2. Why could the B-17 not take evasive action from the IP to the target? Using the four forces of flight and what you know about navigation, explain precisely why a straight-and-level run was required for accurate bombing." />
        <ShortAnswer question="3. The B-17's fuselage and wing skin were thin aluminum — not armor plate. Yet the aircraft was famous for surviving significant battle damage. What design features account for this resilience?" />
      </DayCard>

      <DayCard day={5} week={5} title="Review — Weather and Combat Environment">
        <ShortAnswer question="1. Define: frontal system, icing, ceiling, turbulence." lines={5} />
        <ShortAnswer question="2. How did winter weather affect the Battle of the Bulge? (Connect to Ch. 24-28 in the novel.)" lines={3} />
        <ShortAnswer question="3. Math: A flak shell takes 10.8 seconds to reach 28,000 feet. Destiny's Child is flying at 234 feet per second (160 mph). How far does the aircraft move while the shell is in the air? Show work." lines={5} />
        <ShortAnswer question="4. Why is icing particularly dangerous during the bomb run when the aircraft must fly straight and level?" lines={3} />
      </DayCard>

      <SectionRule />

      {/* =========================================== */}
      {/* WEEK 6 — AVIATION IN THE MODERN WORLD */}
      {/* =========================================== */}
      </section>

      <section className="print-unit">
      <WeekBanner
        week={6}
        title="Modern Aviation — From B-17 to Today"
        subtitle="How WWII built the foundation of modern flight"
        color="blue"
      />

      <DayCard day={1} week={6} title="The Jet Age — From Piston to Turbine">
        <p className="lesson-text">
          The B-17 used piston engines. In the same years it was flying combat missions, German
          engineers produced the world's first operational jet aircraft — the Messerschmitt Me 262,
          introduced in 1944. The jet engine works on a completely different principle: it
          compresses air, adds fuel, ignites it, and expels the high-speed exhaust rearward —
          producing thrust by reaction (Newton's Third Law). Jet engines are more powerful,
          faster, and more efficient at high altitude than piston engines, but far more complex.
          By 1952, piston-engine airliners were being replaced by jets. Today's commercial airliners
          use turbofan jet engines derived directly from those first WWII-era jet experiments.
        </p>
        <VocabGrid>
          <VocabCard term="Turbojet" definition="A jet engine that produces thrust entirely from the exhaust jet. Very fast but fuel-inefficient at lower speeds." />
          <VocabCard term="Turbofan" definition="A jet engine with a large front fan that moves air around the core. More fuel-efficient than turbojet; used on virtually all modern commercial aircraft." />
          <VocabCard term="Newton's Third Law" definition="For every action there is an equal and opposite reaction. Jet exhaust is the action; thrust is the reaction." />
          <VocabCard term="Mach Number" definition="Speed relative to the speed of sound. Mach 1.0 = 767 mph at sea level. B-17 cruise speed: Mach 0.24. Modern airliner: Mach 0.85." />
        </VocabGrid>
        <ShortAnswer question="1. Apply Newton's Third Law to explain how a jet engine produces thrust. Give an analogy from everyday life." />
        <ShortAnswer question="2. The Me 262 was faster than any Allied fighter in 1944. Why did it not decisively change the outcome of the air war over Germany?" lines={3} />
        <ShortAnswer question="3. Compare a turbofan engine to a radial piston engine. What does each one have in common? What is different?" />
      </DayCard>

      <DayCard day={2} week={6} title="GPS and Modern Navigation">
        <p className="lesson-text">
          Eddie Anderson navigated with a sextant, dead reckoning, and radio beacons. Today's
          pilots navigate using GPS — the Global Positioning System. GPS consists of a constellation
          of 31 satellites in medium Earth orbit, each transmitting a precise time signal. A GPS
          receiver on the ground (or in an aircraft) picks up signals from at least four satellites
          simultaneously. By calculating the tiny time differences between the signals (each satellite
          is at a known location), the receiver can compute its precise position to within a few feet.
        </p>
        <ShortAnswer question="1. How many satellites does a GPS receiver need to calculate a 3D position (latitude, longitude, AND altitude)? Why does it need one more than for a 2D position?" lines={3} />
        <ShortAnswer question="2. GPS relies on extremely precise time signals. Why? If a satellite's clock is off by just one microsecond (one millionth of a second), how far off could your position be? (Speed of light = 186,000 miles/second)" lines={5} />
        <ShortAnswer question="3. What might happen to modern aviation if the GPS satellite network were damaged or jammed? How does this compare to the vulnerability of WWII radio navigation to enemy jamming?" />
        <ShortAnswer question="4. If Eddie Anderson had a modern GPS receiver in 1944, how would his job have changed? What parts of his skill set would have become unnecessary? What would still be required?" />
      </DayCard>

      <DayCard day={3} week={6} title="Career Spotlight — Avionics Technician">
        <SidebarBox title="What Does an Avionics Technician Do?">
          Avionics technicians install, inspect, test, adjust, and repair the electronic systems
          aboard aircraft — navigation, communication, autopilot, flight management, radar, and
          more. The FAA requires an Airframe and Powerplant (A&amp;P) certificate plus an Airframe
          Inspector Authorization (IA) for senior technicians. Many avionics techs begin with
          military training (similar to Jack Harris, the crew chief in the novel) or attend an
          FAA-approved aviation maintenance school. Average salary (2024): $73,000-$95,000/year.
          Employment is expected to grow 6% through 2032.
        </SidebarBox>
        <ShortAnswer question="1. Jack Harris, the crew chief in this novel, was awarded the Bronze Star for maintaining Destiny's Child through 53 combat missions. What skills would a WWII crew chief need that are similar to today's avionics technician?" />
        <ShortAnswer question="2. What training or certifications are typically required to become an avionics technician today?" lines={3} />
        <ShortAnswer question="3. If you were designing an avionics curriculum for a homeschool student who wanted to pursue this career, what subjects would you prioritize in high school? (Think about what you have learned in this six-week curriculum.)" lines={5} />
      </DayCard>

      <DayCard day={4} week={6} title="The Legacy of WWII Aviation">
        <p className="lesson-text">
          The technological demands of World War II aviation drove some of the most important
          engineering breakthroughs of the 20th century: pressurized aircraft cabins, turbojet
          propulsion, radar, air traffic control systems, in-flight refueling, ejection seats,
          and the foundations of the FAA's safety systems. Without the B-17 and its successors,
          the modern airline industry as we know it would not exist. The men and women of the
          91st Bomb Group, and thousands of others like them, flew in extraordinary danger to
          test the limits of what was possible — and in doing so, built the world we fly through
          today.
        </p>
        <ShortAnswer question="1. Name three aviation technologies that were developed or advanced during WWII and are still in use today (in modified form)." lines={3} />
        <ShortAnswer question="2. The novel's Historical Note states that Destiny's Child was on its 53rd mission when it was shot down — and that the real crew chief, Jack Gaffney, received the Bronze Star for keeping the aircraft combat-ready through all those missions. What does this tell us about the relationship between ground crews and flight crews?" />
        <EssayBox
          prompt="Final Essay: In 4-6 paragraphs, explain what aviation meant to World War II — and what World War II meant to aviation. Use specific technical facts from this curriculum (engines, navigation, radio, weather) as well as specific scenes from Arms of Deliverance. Conclude with what you believe the legacy of the B-17 era means for the future of flight."
          lines={18}
        />
      </DayCard>

      <DayCard day={5} week={6} title="Final Review and Capstone Assessment">
        <ShortAnswer question="1. Name and define the four forces of flight." lines={5} />
        <ShortAnswer question="2. Explain Bernoulli's Principle and how it generates lift." lines={3} />
        <ShortAnswer question="3. What is dead reckoning? What are its three inputs?" lines={3} />
        <ShortAnswer question="4. Name the four strokes of a piston engine in order." lines={2} />
        <ShortAnswer question="5. What is the difference between airspeed and ground speed? Why does the difference matter for a navigator?" lines={3} />
        <ShortAnswer question="6. Math: A B-17 departs England at 0630. The target is 700 miles away. Cruise speed: 160 mph. Tailwind on the outbound leg: 20 mph. Headwind on the return: 20 mph. What time does the aircraft arrive on target? What time does it return? Show all work." lines={8} />
        <ShortAnswer question="7. How does GPS work, and how does it improve on WWII dead reckoning and celestial navigation?" lines={4} />
        <ShortAnswer question="8. Connect the avionics: How does understanding the B-17's navigation systems, radio, engines, and weather challenges help you appreciate what Eddie Anderson did on his 30th mission? Be specific — name at least three concepts from this curriculum." lines={6} />
      </DayCard>
      </section>

    </div>
  );
}